python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-add.bin               rv32ui-p-add.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-addi.bin              rv32ui-p-addi.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-and.bin               rv32ui-p-and.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-andi.bin              rv32ui-p-andi.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-auipc.bin             rv32ui-p-auipc.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-beq.bin               rv32ui-p-beq.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-bge.bin               rv32ui-p-bge.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-bgeu.bin              rv32ui-p-bgeu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-blt.bin               rv32ui-p-blt.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-bltu.bin              rv32ui-p-bltu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-bne.bin               rv32ui-p-bne.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-fence_i.bin           rv32ui-p-fence_i.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-jal.bin               rv32ui-p-jal.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-jalr.bin              rv32ui-p-jalr.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lb.bin                rv32ui-p-lb.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lbu.bin               rv32ui-p-lbu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lh.bin                rv32ui-p-lh.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lhu.bin               rv32ui-p-lhu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lui.bin               rv32ui-p-lui.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-lw.bin                rv32ui-p-lw.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-or.bin                rv32ui-p-or.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-ori.bin               rv32ui-p-ori.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sb.bin                rv32ui-p-sb.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sh.bin                rv32ui-p-sh.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-simple.bin            rv32ui-p-simple.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sll.bin               rv32ui-p-sll.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-slli.bin              rv32ui-p-slli.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-slt.bin               rv32ui-p-slt.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-slti.bin              rv32ui-p-slti.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sltiu.bin             rv32ui-p-sltiu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sltu.bin              rv32ui-p-sltu.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sra.bin               rv32ui-p-sra.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-srai.bin              rv32ui-p-srai.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-srl.bin               rv32ui-p-srl.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-srli.bin              rv32ui-p-srli.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sub.bin               rv32ui-p-sub.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-sw.bin                rv32ui-p-sw.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-xor.bin               rv32ui-p-xor.init
python3 BinToMem_CLI.py  ../isa/generated/rv32ui-p-xori.bin              rv32ui-p-xori.init
