+define+ISA_TEST_ONE_RAM
$PROJ_BMM/design/test/tb_bmm.sv        
$PROJ_BMM/design/rtl/ram_selfdef.sv    

$PROJ_BMM/design/rtl/bmm_pkg.sv        
$PROJ_BMM/design/rtl/bmm.sv            
$PROJ_BMM/design/rtl/instr_decode.sv   
$PROJ_BMM/design/rtl/instr_fetch.sv    
$PROJ_BMM/design/rtl/pre_decode.sv     
$PROJ_BMM/design/rtl/ras.sv            
$PROJ_BMM/design/rtl/sp_ram.sv         
$PROJ_BMM/design/rtl/instr_issue_1.sv    
//$PROJ_BMM/design/rtl/instr_issue.sv    
$PROJ_BMM/design/rtl/register_file.sv  
$PROJ_BMM/design/rtl/commit.sv         
$PROJ_BMM/design/rtl/ex.sv               
$PROJ_BMM/design/rtl/branch_unit.sv      
$PROJ_BMM/design/rtl/load_store_1.sv          
//$PROJ_BMM/design/rtl/load_store.sv      
$PROJ_BMM/design/rtl/alu.sv              
$PROJ_BMM/design/rtl/csr_ctrl.sv         
$PROJ_BMM/design/rtl/csrfile_and_controller.sv
$PROJ_BMM/design/rtl/csr_file.sv         
$PROJ_BMM/design/rtl/mul_div.sv          
$PROJ_BMM/design/rtl/mul.sv              
$PROJ_BMM/design/rtl/div.sv              
$PROJ_BMM/design/rtl/lzc.sv              
$PROJ_BMM/design/rtl/riscv_crypto_fu_ssm3.sv
$PROJ_BMM/design/rtl/riscv_crypto_fu_ssm4.sv
$PROJ_BMM/design/rtl/riscv_crypto_fu_sboxes.sv
